[package]
name = "tcping_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
trust-dns = "0.22.0"
trust-dns-resolver = "0.22.0"